version: '3'
services: 
    webapi:
        build: 
            context: .
            dockerfile: ./resources/docker/application/dockerfile
        ports: 
        - "3000:3000"
        depends_on:
        - postgres
        environment: 
        - NODE_ENV=production
        - DATABASE_URI=postgres
        - DATABASE_PORT=5432
        command: sh -c "dockerize -wait tcp://postgres:5432 -timeout 300s -wait-retry-interval 1s node index.js"
    postgres:
        build: ./resources/docker/database
        ports: 
        - "5432:5432"